set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(RISCV_TOOL "riscv64-linux-gnu")
set(RISCV_SYSROOT "/usr/riscv64-linux-gnu")
set(GCC_PREFIX "/usr")

set(BUILD_SHARED_LIBS OFF)
set(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++ -lpthread")

set(CMAKE_C_COMPILER   clang)
set(CMAKE_CXX_COMPILER clang++)

set(TRIPLE "--target=${RISCV_TOOL} --gcc-toolchain=${GCC_PREFIX} --sysroot=${RISCV_SYSROOT}")
set(PACKAGES "-pthread")

set(COMMON_FLAGS "${TRIPLE} ${PACKAGES}")

set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS} ${COMMON_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${COMMON_FLAGS}")

message(STATUS "CXX_FLAGS: ${CMAKE_CXX_FLAGS}")

set(CMAKE_SYSROOT ${RISCV_SYSROOT})
set(CMAKE_FIND_ROOT_PATH ${RISCV_SYSROOT})
set(CMAKE_CROSSCOMPILING TRUE)

message(STATUS "CMAKE_SYSROOT: ${CMAKE_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
