set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(RISCV_TOOL "riscv64-linux-gnu")
set(RISCV_SYSROOT "/usr/riscv64-linux-gnu")

set(BUILD_SHARED_LIBS OFF)
set(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++")

set(CMAKE_C_COMPILER "${RISCV_TOOL}-gcc")
set(CMAKE_CXX_COMPILER "${RISCV_TOOL}-g++")

set(CMAKE_SYSROOT ${RISCV_SYSROOT})
set(CMAKE_FIND_ROOT_PATH ${RISCV_SYSROOT})

message(STATUS "CMAKE_SYSROOT: ${CMAKE_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
