set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")

set(RISCV_TOOL "riscv64-linux-gnu")
set(RISCV_SYSROOT "/usr/riscv64-linux-gnu")

set(CMAKE_C_COMPILER "${RISCV_TOOL}-gcc")
set(CMAKE_CXX_COMPILER "${RISCV_TOOL}-g++")

set(CMAKE_SYSROOT ${RISCV_SYSROOT})
set(CMAKE_FIND_ROOT_PATH ${RISCV_SYSROOT})

message(STATUS "CMAKE_SYSROOT: ${CMAKE_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
