import os

shared_variables = {
    "HTOP": 0,
    "STOP": 1,
    "ARENA": 2,
    "ARENA_SIZE": 3
}

if __name__ == '__main__':
    # assert that we can actually index into them with the syntax
    # ld reg, num(reg2)
    # i.e we are checking that we never have a num that is out of bounds
    assert (len(shared_variables) * 8 < 2048)

    with open("shared_variables.h", "w") as f:
        f.write(f"// THIS FILE IS GENERATED BY {os.path.basename(__file__)}\n")
        f.write("// DO NOT EDIT\n\n")
        f.write(f"const int SHARED_FIELDS = {len(shared_variables)};\n\n")

        f.write("enum PCBSharedFields {\n")
        for key, index in shared_variables.items():
            f.write(f"  {key} = {index},\n")

        f.write("};")
