import sys
import os
import subprocess
from pathlib import Path
from meta_assembly_compile import do_compile

project_root = Path(sys.argv[1])
callable_fun_file = Path(sys.argv[2])


def enum_and_case_from(file: Path):
    assert (file.is_file())

    script_dir = os.path.dirname(os.path.abspath(__file__))
    script_path = os.path.join(script_dir, 'get_binary.sh')
    result = subprocess.run([script_path, file, callable_fun_file],
                            text=True, capture_output=True)

    if result.returncode != 0:
        print(result.stderr)
        exit(1)

    byte_array_str = result.stdout.strip()

    # get enum name from file
    enum_name = f"{file.name[:-2]}_SNIP".upper()

    case_text = (
        f"  case {enum_name}:\n"
        f"    return {byte_array_str};\n\n"
    )

    return f"  {enum_name}, // {file.relative_to(project_root)}\n", case_text


generated_tag = f"// THIS FILE WAS GENERATED BY {Path(__file__).name}\n"

header_out_file = Path(sys.argv[5])
assert (header_out_file.is_file() or not header_out_file.exists())

include_part = project_root / "include"
include_line = f"#include \"{
    header_out_file.relative_to(include_part)}\"\n"

src_starting_lines = """#include <glog/logging.h>

std::vector<uint8_t> get_riscv(AsmSnippet snippet) {
  switch (snippet) {

"""

src_ending_line = """  default:
    LOG(FATAL) << "AsmSnippet " << snippet << " does not exist.";
  }
}
"""

header_starting_lines = """#ifndef INSTR_CODE_H
#define INSTR_CODE_H

#include <cstdint>
#include <vector>

enum AsmSnippet {
"""

header_ending_lines = """};

std::vector<uint8_t> get_riscv(AsmSnippet snippet);

#endif
"""

header_lines = [generated_tag, header_starting_lines]
src_lines = [generated_tag, include_line, src_starting_lines]

asm_directory = Path(sys.argv[3])
assert (asm_directory.is_dir())

build_directory = asm_directory / "build"

# clear build dir
for file in build_directory.iterdir():
    if file.is_file():
        file.unlink()

for file in asm_directory.glob("*_m.S"):
    do_compile(file, callable_fun_file)


for file in build_directory.glob("*.S"):
    enum_option, switch_case = enum_and_case_from(file)
    src_lines.append(switch_case)
    header_lines.append(enum_option)

src_lines.append(src_ending_line)
header_lines.append(header_ending_lines)

src_out_file = Path(sys.argv[4])
assert (src_out_file.is_file() or not src_out_file.exists())

with open(src_out_file, "w") as f:
    f.writelines(src_lines)

with open(header_out_file, "w") as f:
    f.writelines(header_lines)
