import os
import sys
from shared_variables import shared_variables

shared_variable_file = sys.argv[1]

with open(shared_variable_file, "w") as f:
    f.write(f"// THIS FILE IS GENERATED BY {os.path.basename(__file__)}\n")
    f.write("// DO NOT EDIT\n\n")
    f.write(f"const int SHARED_FIELDS = {len(shared_variables)};\n\n")

    f.write("enum PCBSharedFields {\n")
    for key, index in shared_variables.items():
        f.write(f"  {key} = {index},\n")

    f.write("};")
